version = "3.11.4"

runner.dialect = scala3
runner.dialectOverride.allowSignificantIndentation = false

maxColumn = 150

newlines.implicitParamListModifierPrefer = before

continuationIndent.defnSite = 2
continuationIndent.extendSite = 2

indentOperator.excludeRegex = "^$"

align.preset = most

docstrings.style = SpaceAsterisk
docstrings.oneline = unfold
docstrings.blankFirstLine = yes
docstrings.wrap = no

rewrite.rules = [Imports, RedundantBraces, RedundantParens, SortModifiers, PreferCurlyFors]
rewrite.imports.groups = [
  ["javax?\\..*"],
  ["scala\\..*"],
  [".*"],
  ["sage\\..*"],
]
rewrite.imports.sort = scalastyle
rewrite.redundantBraces.stringInterpolation = true
