package sage.integration.commands

/**
  * The acknowledged command-coverage partition. `skipped` is deliberate-never with reasons; `todo` is the honest gap, regenerable by
  * diffing a live server against the implemented samples. The coverage spec fails on any unacknowledged drift.
  */
object Coverage {

  val skipped: Map[String, String] = Map(
    "GETSET"               -> "deprecated: SET with setGet subsumes it",
    "SETNX"                -> "deprecated: SET with SetCondition.IfNotExists",
    "SETEX"                -> "deprecated: SET with SetExpiry.In",
    "PSETEX"               -> "deprecated: SET with SetExpiry.In",
    "SUBSTR"               -> "deprecated: GETRANGE",
    "HMSET"                -> "deprecated: HSET takes multiple field/value pairs",
    "RPOPLPUSH"            -> "deprecated: LMOVE",
    "ZRANGEBYSCORE"        -> "deprecated: ZRANGE with ByScore",
    "ZRANGEBYLEX"          -> "deprecated: ZRANGE with ByLex",
    "ZREVRANGE"            -> "deprecated: ZRANGE with ByRank and rev",
    "ZREVRANGEBYSCORE"     -> "deprecated: ZRANGE with ByScore and rev",
    "ZREVRANGEBYLEX"       -> "deprecated: ZRANGE with ByLex and rev",
    "OBJECT ENCODING"      -> "implemented as OBJECT; the subcommand is an argument, not a separate Command name",
    "OBJECT FREQ"          -> "implemented as OBJECT; the subcommand is an argument, not a separate Command name",
    "OBJECT IDLETIME"      -> "implemented as OBJECT; the subcommand is an argument, not a separate Command name",
    "OBJECT REFCOUNT"      -> "implemented as OBJECT; the subcommand is an argument, not a separate Command name",
    "PUBSUB CHANNELS"      -> "implemented as PUBSUB; the subcommand is an argument, not a separate Command name",
    "PUBSUB NUMSUB"        -> "implemented as PUBSUB; the subcommand is an argument, not a separate Command name",
    "PUBSUB NUMPAT"        -> "implemented as PUBSUB; the subcommand is an argument, not a separate Command name",
    "SUBSCRIBE"            -> "delivered via the subscribe stream API, not a runnable command",
    "PSUBSCRIBE"           -> "delivered via the pSubscribe stream API, not a runnable command",
    "SSUBSCRIBE"           -> "delivered via the sSubscribe stream API, not a runnable command",
    "UNSUBSCRIBE"          -> "sent by the subscribe stream's scope closure, not a runnable command",
    "PUNSUBSCRIBE"         -> "sent by the pSubscribe stream's scope closure, not a runnable command",
    "SUNSUBSCRIBE"         -> "sent by the sSubscribe stream's scope closure, not a runnable command",
    "PUBSUB SHARDCHANNELS" -> "implemented as PUBSUB; the subcommand is an argument, not a separate Command name",
    "PUBSUB SHARDNUMSUB"   -> "implemented as PUBSUB; the subcommand is an argument, not a separate Command name",
    "MULTI"                -> "driven by the transaction scope API, not a runnable command",
    "EXEC"                 -> "driven by the transaction scope API, not a runnable command",
    "WATCH"                -> "driven by the transaction scope API, not a runnable command",
    "UNWATCH"              -> "driven by the transaction scope API, not a runnable command",
    "ASKING"               -> "issued by cluster ASK-redirect handling, not a runnable command",
    "CLUSTER SLOTS"        -> "issued by cluster topology discovery, not a runnable command",
    "CLIENT TRACKING"      -> "enabled at connection bootstrap for client-side caching, not a runnable command",
    "CLIENT CACHING"       -> "issued by the cached-read API before each tracked read, not a runnable command",
    "CLIENT TRACKINGINFO"  -> "tracking is configured via the cached-read API; introspection is not exposed as a command",
    "BRPOPLPUSH"           -> "deprecated: BLMOVE",
    "PSYNC"                -> "replication protocol between servers, never issued by a client",
    "SYNC"                 -> "replication protocol between servers, never issued by a client",
    "REPLCONF"             -> "replication protocol between servers, never issued by a client",
    "REPLICAOF"            -> "server replication administration, out of scope",
    "SLAVEOF"              -> "deprecated replication administration (REPLICAOF), out of scope",
    "FAILOVER"             -> "server failover administration, out of scope",
    "SHUTDOWN"             -> "server lifecycle administration, out of scope",
    "MONITOR"              -> "debugging firehose that hijacks the connection, out of scope",
    "DEBUG"                -> "server debugging command, out of scope",
    "LOLWUT"               -> "easter-egg command, no client API",
    "SELECT"               -> "changing the selected DB on the shared Multiplexed Connection would affect all fibers; unsupported",
    "SWAPDB"               -> "whole-database administration, out of scope",
    "QUIT"                 -> "deprecated: close the client instead of sending QUIT",
    "RESET"                -> "would reset state on the shared Multiplexed Connection across all fibers; not exposed",
    "DISCARD"              -> "the transaction scope abandons by dropping its connection, not via DISCARD"
  )

  val todo: Set[String] = Set(
    "ACL",
    "ACL CAT",
    "ACL DELUSER",
    "ACL DRYRUN",
    "ACL GENPASS",
    "ACL GETUSER",
    "ACL HELP",
    "ACL LIST",
    "ACL LOAD",
    "ACL LOG",
    "ACL SAVE",
    "ACL SETUSER",
    "ACL USERS",
    "ACL WHOAMI",
    "ARCOUNT",
    "ARDEL",
    "ARDELRANGE",
    "ARGET",
    "ARGETRANGE",
    "ARGREP",
    "ARINFO",
    "ARINSERT",
    "ARLASTITEMS",
    "ARLEN",
    "ARMGET",
    "ARMSET",
    "ARNEXT",
    "AROP",
    "ARRING",
    "ARSCAN",
    "ARSEEK",
    "ARSET",
    "AUTH",
    "BGREWRITEAOF",
    "BGSAVE",
    "BITCOUNT",
    "BITFIELD",
    "BITFIELD_RO",
    "BITOP",
    "BITPOS",
    "CLIENT",
    "CLIENT CAPA",
    "CLIENT GETNAME",
    "CLIENT GETREDIR",
    "CLIENT HELP",
    "CLIENT ID",
    "CLIENT IMPORT-SOURCE",
    "CLIENT INFO",
    "CLIENT KILL",
    "CLIENT LIST",
    "CLIENT NO-EVICT",
    "CLIENT NO-TOUCH",
    "CLIENT PAUSE",
    "CLIENT REPLY",
    "CLIENT SETINFO",
    "CLIENT SETNAME",
    "CLIENT UNBLOCK",
    "CLIENT UNPAUSE",
    "CLUSTER",
    "CLUSTER ADDSLOTS",
    "CLUSTER ADDSLOTSRANGE",
    "CLUSTER BUMPEPOCH",
    "CLUSTER COUNT-FAILURE-REPORTS",
    "CLUSTER COUNTKEYSINSLOT",
    "CLUSTER DELSLOTS",
    "CLUSTER DELSLOTSRANGE",
    "CLUSTER FAILOVER",
    "CLUSTER FLUSHSLOTS",
    "CLUSTER FORGET",
    "CLUSTER GETKEYSINSLOT",
    "CLUSTER HELP",
    "CLUSTER INFO",
    "CLUSTER KEYSLOT",
    "CLUSTER LINKS",
    "CLUSTER MEET",
    "CLUSTER MIGRATION",
    "CLUSTER MYID",
    "CLUSTER MYSHARDID",
    "CLUSTER NODES",
    "CLUSTER REPLICAS",
    "CLUSTER REPLICATE",
    "CLUSTER RESET",
    "CLUSTER SAVECONFIG",
    "CLUSTER SET-CONFIG-EPOCH",
    "CLUSTER SETSLOT",
    "CLUSTER SHARDS",
    "CLUSTER SLAVES",
    "CLUSTER SLOT-STATS",
    "CLUSTER SYNCSLOTS",
    "COMMAND",
    "COMMAND COUNT",
    "COMMAND DOCS",
    "COMMAND GETKEYS",
    "COMMAND GETKEYSANDFLAGS",
    "COMMAND HELP",
    "COMMAND INFO",
    "COMMAND LIST",
    "COMMANDLOG",
    "COMMANDLOG GET",
    "COMMANDLOG HELP",
    "COMMANDLOG LEN",
    "COMMANDLOG RESET",
    "CONFIG",
    "CONFIG GET",
    "CONFIG HELP",
    "CONFIG RESETSTAT",
    "CONFIG REWRITE",
    "CONFIG SET",
    "DBSIZE",
    "ECHO",
    "EVAL",
    "EVAL_RO",
    "EVALSHA",
    "EVALSHA_RO",
    "FCALL",
    "FCALL_RO",
    "FLUSHALL",
    "FLUSHDB",
    "FUNCTION",
    "FUNCTION DELETE",
    "FUNCTION DUMP",
    "FUNCTION FLUSH",
    "FUNCTION HELP",
    "FUNCTION KILL",
    "FUNCTION LIST",
    "FUNCTION LOAD",
    "FUNCTION RESTORE",
    "FUNCTION STATS",
    "GEOADD",
    "GEODIST",
    "GEOHASH",
    "GEOPOS",
    "GEORADIUS",
    "GEORADIUS_RO",
    "GEORADIUSBYMEMBER",
    "GEORADIUSBYMEMBER_RO",
    "GEOSEARCH",
    "GEOSEARCHSTORE",
    "GETBIT",
    "HOTKEYS",
    "HOTKEYS GET",
    "HOTKEYS HELP",
    "HOTKEYS RESET",
    "HOTKEYS START",
    "HOTKEYS STOP",
    "INFO",
    "LASTSAVE",
    "LATENCY",
    "LATENCY DOCTOR",
    "LATENCY GRAPH",
    "LATENCY HELP",
    "LATENCY HISTOGRAM",
    "LATENCY HISTORY",
    "LATENCY LATEST",
    "LATENCY RESET",
    "MEMORY",
    "MEMORY DOCTOR",
    "MEMORY HELP",
    "MEMORY MALLOC-STATS",
    "MEMORY PURGE",
    "MEMORY STATS",
    "MEMORY USAGE",
    "MODULE",
    "MODULE HELP",
    "MODULE LIST",
    "MODULE LOAD",
    "MODULE LOADEX",
    "MODULE UNLOAD",
    "OBJECT HELP",
    "PFADD",
    "PFCOUNT",
    "PFDEBUG",
    "PFMERGE",
    "PFSELFTEST",
    "PUBSUB HELP",
    "READONLY",
    "READWRITE",
    "RESTORE-ASKING",
    "ROLE",
    "SAVE",
    "SCRIPT",
    "SCRIPT DEBUG",
    "SCRIPT EXISTS",
    "SCRIPT FLUSH",
    "SCRIPT HELP",
    "SCRIPT KILL",
    "SCRIPT LOAD",
    "SCRIPT SHOW",
    "SETBIT",
    "SLOWLOG",
    "SLOWLOG GET",
    "SLOWLOG HELP",
    "SLOWLOG LEN",
    "SLOWLOG RESET",
    "TIME",
    "TRIMSLOTS",
    "WAIT",
    "WAITAOF",
    "XACK",
    "XACKDEL",
    "XADD",
    "XAUTOCLAIM",
    "XCFGSET",
    "XCLAIM",
    "XDEL",
    "XDELEX",
    "XGROUP",
    "XGROUP CREATE",
    "XGROUP CREATECONSUMER",
    "XGROUP DELCONSUMER",
    "XGROUP DESTROY",
    "XGROUP HELP",
    "XGROUP SETID",
    "XIDMPRECORD",
    "XINFO",
    "XINFO CONSUMERS",
    "XINFO GROUPS",
    "XINFO HELP",
    "XINFO STREAM",
    "XLEN",
    "XNACK",
    "XPENDING",
    "XRANGE",
    "XREAD",
    "XREADGROUP",
    "XREVRANGE",
    "XSETID",
    "XTRIM"
  )
}
